# NumPy Basics: Exercise Notebook

### Exercise 1
Create a 1D NumPy array of numbers from 0 to 9.

In [2]:
# Your code here
import numpy as np
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercise 2
Create a 2D NumPy array of shape (3,3) with all elements equal to 5.

In [3]:
# Your code here
arr1 = np.full((3,3), 5)
arr1


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### Exercise 3
Create a 1D array of 10 zeros.

In [4]:
# Your code here
arr2 = np.zeros(10)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Exercise 4
Create a 1D array of 10 ones.

In [5]:
# Your code here
arr3 = np.ones(10)
arr3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Exercise 5
Create a 1D array of 10 random integers between 1 and 50.

In [15]:
# Your code here
arr4 = np.random.randint(1, 51, size=10)
arr4

array([21, 48, 42, 36,  7, 21, 46, 13, 14,  2])

### Exercise 6
Check the shape and data type of the array you just created.

In [10]:
# Your code here
arr4.shape
arr4.dtype


dtype('float64')

### Exercise 7
Reshape a 1D array of numbers 0 to 11 into a 3x4 matrix.

In [21]:
# Your code here
arr5 = np.arange(12)
reshaped = arr5.reshape((3,4))
reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Exercise 8
Compute the sum of all elements in the above 3x4 array.

In [23]:
# Your code here
total_sum = arr5.sum()
total_sum

np.int64(66)

### Exercise 9
Compute the mean of all elements in the 3x4 array.

In [26]:
# Your code here
mean_value = np.mean(arr5)
mean_value

np.float64(5.5)

### Exercise 10
Find the maximum value in the 3x4 array.

In [27]:
# Your code here
max_value = np.max(arr5)
max_value

np.int64(11)

### Exercise 11
Create an array [1,2,3,4,5] and multiply each element by 10.

In [29]:
# Your code here
arr6 = np.array([1,2,3,4,5])
multiply = arr6 * 10
multiply

array([10, 20, 30, 40, 50])

### Exercise 12
Create an array [10,20,30,40,50] and subtract 5 from each element.

In [30]:
# Your code here
arr7 = np.array([10,20,30,40,50])
subtract = arr7 - 5
subtract

array([ 5, 15, 25, 35, 45])

### Exercise 13
Add two arrays element-wise: [1,2,3] and [4,5,6].

In [32]:
# Your code here
arr8 = np.array([1,2,3])
arr9 = np.array([4,5,6])
Sum_of_arrays = arr8 + arr9
Sum_of_arrays

array([5, 7, 9])

### Exercise 14
Multiply two arrays element-wise: [1,2,3] and [4,5,6].

In [34]:
# Your code here
arr10 = np.array([1,2,3])
arr11 = np.array([4,5,6])
mul_of_arrays = arr10 * arr11
mul_of_arrays

array([ 4, 10, 18])

### Exercise 15
Generate a 1D array of 6 equally spaced numbers between 0 and 1.

In [37]:
# Your code here
arr12 = np.linspace(0, 10, 6)
arr12

array([ 0.,  2.,  4.,  6.,  8., 10.])

### Exercise 16
Create a 4x4 identity matrix.

In [39]:
# Your code here
identity_matrix = np.identity(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Exercise 17
Transpose the 3x4 matrix created earlier.

In [46]:
# Your code here
arr_transpose = np.arange(12).reshape(3,4)
arr_transpose.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Exercise 18
Flatten the 3x4 matrix into a 1D array.

In [42]:
# Your code here
matrix = np.arange(12).reshape(3,4)
Flattened_matrix = matrix.flatten()
Flattened_matrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Exercise 19
Check which elements in the 3x4 matrix are greater than 5.

In [47]:
# Your code here
arr12 = np.arange(12).reshape(3,4)
greater = arr12 > 5
greater

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

### Exercise 20
Replace all elements greater than 5 in the 3x4 matrix with 0.

In [50]:
# Your code here
arr13 = np.arange(12).reshape(3,4)
arr13[arr13 > 5] = 0
arr13

array([[0, 1, 2, 3],
       [4, 5, 0, 0],
       [0, 0, 0, 0]])